name: Generate Dgeni Documentation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: npx gulp assets dgeni # Updated to run Gulp directly

      - name: Output generated files
        run: |
          mkdir -p output
          cp -R build/* output/

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dgeni-docs
          path: output/
