name: Generate Dgeni Documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: |
          npm run gulp assets dgeni # Adjust this command based on your setup

      - name: Output generated files
        run: |
          mkdir -p output
          cp -R build/* output/ # Copy the generated files to an output folder

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dgeni-docs
          path: output/
